# Site settings
title: Mücahit İNEL
description: 'Hey! I will publish my resume and some blogs anymore'
url: 'https://minel.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mücahit İNEL'
  email: mucahit.in@gmail.com
  twitter_username: mucahit_inel
  facebook_username: mucahit.in
  github_username:  minel
  linkedin_username:  mucahit_inel

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
